config/routes.rb
Simpleslots::Application.routes.draw do
  devise_for :users

  resources :games

  resources :users
  
  root :to => "users#show"

end

app/models/game.rb
class Game < ActiveRecord::Base
  
  belongs_to :user
  
  attr_accessible :payout, :default => 0 
  attr_accessible :wager
  
  serialize :reels
  
  after_initialize :init_reels
  
  REEL_VALUES = [1,2,3,4,5,6,7,8,9]
  
  def init_reels
    self.reels = [0,0,0]
  end
  
  def play(wager)
    user.spend(wager)
    self.wager = wager
    self.reels = [REEL_VALUES.sample, REEL_VALUES.sample, REEL_VALUES.sample]
    self.payout = reels.uniq.length == 1 ? wager * reels[0] : 0
    user.win(payout)
    self.save
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,:token_authenticatable, :registerable, :recoverable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  attr_accessible :balance,  :default => 5000
  has_many :games, :dependent => :destroy
  
  def spend(amount)
    self.balance = self.balance - amount
    self.save
  end
  
  def win(amount)
    self.balance = self.balance + amount
    self.save
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :set_user
  
  # def index
  #   @games = Game.all
  # end

  def show
    @user = current_user
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game)
    else
      flash[:alert] = "Whoops, something went wrong. Try again!"
      redirect_to :controller => 'users', :action => 'show', :id => current_user.id
    end
  end
  
  def update
    puts params
    @game = Game.find(params[:id])
    @game.play(params[:wager].to_i) if params[:wager]
    puts '---'
    puts @game.to_yaml
    puts '---'
    render :json => @game
  end

  def set_user
    @user = current_user
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    if !params[:id]
      @user = current_user
    else
      @user = User.find(params[:id])
    end
  end
  
  def edit
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wager %><br />
    <%= f.number_field :wager %>
  </div>
  <div class="field">
    <%= f.label :payout %><br />
    <%= f.number_field :payout %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_reels.html.erb
<span id='reel_1' class='reel'><%= @game.reels[0]%></span>
<span id='reel_2' class='reel'><%= @game.reels[1]%></span>
<span id='reel_3' class='reel'><%= @game.reels[2]%></span>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Wager</th>
    <th>Payout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.wager %></td>
    <td><%= game.payout %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div id='reels'><%= render :partial => 'reels' %></div>

<div>
	<b>Balance:</b> <%= @user.balance %>
</div>

<%= form_for @game, :url => {:action => 'update'}, remote: true, :format => :json do |f| %>
	<div data-role='fieldcontain'>
		<label for='wager'>Wager:</label>
		<input name='wager' id='wager' min="10" max="250" value="100" step="10" type="range" data-highlight='true'>
	</div>
	<%= f.hidden_field 'id', :value => @game.id %>
	<%= link_to 'Spin!', game_path(@game), :class => 'btn btn-primary btn-large'%>
<% end %>

<br />
<br />
<br />

<pre>
	<%= @game.to_yaml %>
</pre>

app/views/games/update.js.erb
$('#reels').html("<%= escape_javascript(render(reels)) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleslots</title>
  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application', 'bootstrap.min' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class='navbar navbar-inner'>
		<span id='account_options'>
			<ul class='nav nav-pills pull-right'>
				<% if user_signed_in? %>
				<li>
					<%= link_to "#{current_user.username}'s account", user_path(current_user) %>
				</li>
				<li>
					<%= link_to 'Logout', destroy_user_session_path, :method => :delete %>        
				</li>
				<% else %>
				<li>
					<%= link_to 'Login', new_user_session_path  %>  
	  		</li>
				<% end %>
			</ul>
		</span>
	</div>

	<div class='flash'>
		<p class='notice'><%= notice %></p>
		<!-- <p class='alert'><%= alert %></p> -->
	</div>

	<div id='main' class='row-fluid'>
		<%= yield %>
	</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
			<ul>
			<% @user.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<div id='edit_user_fields' class='row-fluid'>
		<div class="field">
			<%= f.text_field :username, :placeholder => @user.username %>
		</div>
		<div class="field">
			<%= f.email_field :email, :placeholder => @user.email %>
		</div>
		<div class="field">
			<%= f.text_field :password, :placeholder => 'Password - unchanged if blank' %>
		</div>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Info</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Balance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.balance %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div id='user_info'>
	<p>
		<b>Username:</b> <%= @user.username %>
	</p>

	<p>
		<b>Balance:</b> <%= @user.balance %>
	</p>
	<p>
		<b>Games Played:</b> <%= @user.games.count %>
	</p>
	<%= link_to 'edit my info', edit_user_path(@user) %>
</div>
<br />
<br />
<div>
	<%= button_to 'Play Now!', games_path, :class => 'btn btn-primary btn-large'%>
</div>